name: Build and Publish Docker Image

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to use Node.js 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated to use Node.js 20

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Updated to use Node.js 20
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5  # Updated to use Node.js 20
        with:
          context: .
          push: true
          tags: devros42/monero-full-node:latest
